feature/an/cardGroup
monsterkosh/jeremy-project pull request #4
Opened 2021-11-04 19:56 UTC by nicolino1

-added styles to CardGroup and Card components.
- Mobile and desktop views finished.

2021-11-04 20:03 UTC, monsterkosh commented on src/components/CardGroup/CardGroup.css
> +
delete empty line

2021-11-04 20:04 UTC, monsterkosh commented on src/components/Cards/Card.css
> +    font-size: 18px;
dont use px on font-size

2021-11-04 20:05 UTC, monsterkosh commented on src/components/Cards/Card.css
> +    font-size: 40px;
change px to rem

2021-11-04 20:05 UTC, monsterkosh commented on src/components/Cards/Card.css
> +    font-size: 14px;
px to rem

2021-11-04 20:06 UTC, monsterkosh requested changes
small changes to font size unit

2021-11-04 20:35 UTC, Gastonben reviewed
After revisions LGTM.

2021-11-05 12:33 UTC, monsterkosh approved these changes
LGTM

2021-11-05 12:34 UTC, Gastonben approved these changes
LGTM

2021-11-05 12:34 UTC, merged